### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by andreipet** [novotnyr/maven-jetty-spring-slf4j-demo#1]
Hello.
I ran the demo and jetty still logs with another logback.xml (I think).
Can you still use this demo?

**Comment by novotnyr** [comment]
Could you be more specific with your trouble. Even better, do you have an example of log statements emitted by Jetty and that another logback.xml of yours?

**Comment by novotnyr** [comment]
OK, I have made some investigations. When using Maven 3.0.x, this positively works. However, Maven 3.1.x has migrated its internal logging framework to `slf4j`. You may use `conf\logging\simplelogger.properties` file in the Maven installation folder to customize logging. This is explained in Maven docs: http://maven.apache.org/maven-logging.html

**Comment by andreipet** [comment]
10x man.
Sorry for my late reply.
I saw that too. (slf4f logging).
I guess it's ok after all to use maven-plugin logging when we use maven
plugins.
Even if it would be nicer to have an option on plugin to set its logging
 options :)
